INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Marcos', 'Magaña', 'marcosmh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Hector', 'Niño', 'hector@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Gildardo', 'Perez', 'gildardo@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Juan', 'Jimenez', 'juan@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Mario', 'Cordova', 'mario@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jorge', 'Rosales', 'jorgeh@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jesus', 'Cano', 'jesus@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Neyser', 'De la Cruz', 'neyser@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ademir', 'Montero', 'ademir@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Jose', 'Perez', 'jose@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Rosalinda', 'Alvarez', 'rosalinda@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Martha', 'Garcia', 'matha@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Susana', 'De la Fuente', 'susana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Ana', 'Fernandez', 'ana@dev.net', '2020-05-12');
INSERT INTO clientes(nombre,apellido,email,create_at) values('Carmen', 'Hernandez', 'carmen@dev.net', '2020-05-12');